openapi: 3.0.0
info:
  title: Pricing API
  version: 1.0.0
paths:
  /price:
    get:
      summary: Retrieve price information based on criteria
      parameters:
        - name: productId
          in: query
          description: The ID of the product
          required: true
          schema:
            type: integer
            example: 1
        - name: brandId
          in: query
          description: The ID of the brand
          required: true
          schema:
            type: integer
            example: 1
        - name: applicationDate
          in: query
          description: The application date for the price query
          required: true
          schema:
            type: string
            format: date-time
            example: "2020-08-03T10:00:00"
      responses:
        '200':
          description: Successfully retrieved price information
          content:
            application/json:
              schema:
                type: object
                properties:
                  productId:
                    type: integer
                  brandId:
                    type: integer
                  priceRateDescription:
                    type: string
                  startDate:
                    type: string
                    format: date-time
                  endDate:
                    type: string
                    format: date-time
                  price:
                    type: number
                    format: float
                required:
                  - productId
                  - brandId
                  - priceRateDescription
                  - startDate
                  - endDate
                  - price
        '400':
          description: Bad request
        '500':
          description: Internal server error
